<html>
<head>
<title>Costarricense_paso_API REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>Costarricense_paso_API REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Cat_Encaste</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/cat_encaste/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/cat_encaste/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/cat_encaste/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/cat_encaste/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/cat_encaste/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Cat_Horse_Sex</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/cat_horse_sex/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/cat_horse_sex/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/cat_horse_sex/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/cat_horse_sex/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/cat_horse_sex/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Cat_Membership</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/cat_membership/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/cat_membership/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/cat_membership/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/cat_membership/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/cat_membership/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Cat_Person_Type</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/cat_person_type/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/cat_person_type/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/cat_person_type/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/cat_person_type/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/cat_person_type/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Horse</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/horse/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/horse/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/horse/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/horse/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/horse/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Horse_Old_Owner</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/horse_old_owner/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/horse_old_owner/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/horse_old_owner/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/horse_old_owner/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/horse_old_owner/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Horse_Parents</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/horse_parents/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/horse_parents/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/horse_parents/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/horse_parents/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/horse_parents/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Person</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/person/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/person/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/person/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/person/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/person/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Person_Membership</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/person_membership/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/person_membership/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/person_membership/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/person_membership/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/person_membership/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
